; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ESP32_2432S028R_ILI9341

[common]
build_flags =
	-D USER_SETUP_LOADED=1
lib_deps =
	bodmer/TFT_eSPI@^2.5.43
	jchristensen/Timezone@^1.2.6
  https://github.com/Bodmer/OpenWeather
  https://github.com/Bodmer/JSON_Decoder
  https://github.com/Bodmer/TJpg_Decoder

[env:ESP32_2432S028R_ILI9341]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
build_flags =
	${common.build_flags}
	-include src/Setup_ESP32_2432S028R_ILI9341.h
lib_deps =
	${common.lib_deps}

[env:ESP32_2432S028R_ST7789]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
build_flags =
	${common.build_flags}
	-include src/Setup_ESP32_2432S028R_ST7789.h
lib_deps =
	${common.lib_deps}
